export enum MovementType {
    Slide = "slide",
    Push = "push",
    Teleport = "teleport",
    Pull = "pull",
    Walk = "walk",
    Burrow = "burrow",
    Dig = "dig",
    Climb = "climb",
    Swim = "swim",
    Jump = "jump",
    Crawl = "crawl",
    Fly = "fly",
    Hover = "hover",
}